name: cs-archive

services:
  postgres:
    container_name: postgres-cs-archive
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - base

networks:
  base:
    driver: bridge

volumes:
  postgres_data:
